### ISSUE TITLE
/portfolio images render small in non-chrome browser

### ISSUE THREAD

**Issue by kellyky** [kellyky/Portfolio#5]
Ok on Chrome, Brave, Safari, DuckDuckGo -

Problematic on Firefox (right):
<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/87a91eed-9d57-43e3-815c-a508d6b5f6e2" />

**Comment by kellyky** [comment]
Fixed by setting flex-shrink to 0.

```css
/* Portfolio images 'shrink' in Firefox, Zen browsers */
img {
  flex-shrink: 0;
}
```

I am not sure if I will want to set this more "locally" to the Portfolio images, but so far, I think it is ok.
